[package]
name = "gravel-ffi"
version.workspace = true
edition.workspace = true

[dependencies]
gravel-ffi-macros = { path = "../gravel-ffi-macros" }

abi_stable.workspace = true
figment = { workspace = true, features = ["yaml"] }
log.workspace = true
serde.workspace = true

[dev-dependencies]
gravel-test-utils = { path = "../gravel-test-utils" }
gravel-core = { path = "../gravel-core" }

[lints]
workspace = true
