[package]
name = "gravel-provider-calculator"
version = "0.0.0"
edition = "2021"

[dependencies]
gravel-core = { path = "../gravel-core" }

arboard = "3.2.1"
evalexpr = "11.1.0"
serde.workspace = true

[dev-dependencies]
rstest.workspace = true
