[package]
name = "gravel-provider-calculator"
version.workspace = true
edition.workspace = true

[dependencies]
gravel-core = { path = "../gravel-core" }

arboard.workspace = true
log.workspace = true
mexprp.workspace = true
serde.workspace = true

[dev-dependencies]
rstest.workspace = true
