[package]
name = "gravel-provider-calculator"
version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
no-root = []

[dependencies]
gravel-ffi = { path = "../gravel-ffi" }

abi_stable.workspace = true
mexprp.workspace = true
serde.workspace = true

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
