[package]
name = "gravel-provider-calculator"
version.workspace = true
edition.workspace = true

[dependencies]
gravel-ffi = { path = "../gravel-ffi" }

abi_stable.workspace = true
arboard.workspace = true
log.workspace = true
mexprp.workspace = true
serde.workspace = true

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
