[package]
name = "gravel-provider-calculator"
version = "0.0.0"
edition = "2021"

[dependencies]
gravel-core = { path = "../gravel-core" }

arboard = "3.2.1"
mexprp = {version = "0.3.1", default-features = false}
serde.workspace = true

[dev-dependencies]
rstest.workspace = true
