[workspace]
resolver = "2"

members = [
	"gravel",
	"gravel-core",
	"gravel-frontend-default",
	"gravel-provider-calculator",
	"gravel-provider-kill",
	"gravel-provider-program",
	"gravel-provider-system",
	"gravel-provider-websearch",
]

[profile.release]
strip = true
lto = true
