[workspace]
resolver = "2"

members = [
	"gravel",
	"gravel-core",
	"gravel-frontend-fltk",
	"gravel-provider-calculator",
	"gravel-provider-kill",
	"gravel-provider-program",
	"gravel-provider-system",
	"gravel-provider-websearch",
]

[workspace.dependencies]
anyhow = "1.0.75"
itertools = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.19"
rstest = "0.18.2"
serde = "1.0.188"
shellexpand = "3.1.0"
thiserror = "1.0.56"
winapi = "0.3.9"

[profile.release]
strip = true
lto = true
