[config]
skip_core_tasks = true

[tasks.ci-ubuntu]
run_task = { name = ["release-deb", "release-tar", "release-config"] }

[tasks.ci-arch]
run_task = { name = ["release-archpkg"] }

[tasks.ci-windows]
run_task = { name = ["release-zip", "release-msi"] }

# NOTE: github actions windows-2022 has a super old grep version so don't use it without LC_ALL=en_US.utf8
[tasks.patch-version]
script_runner = "sh"
script = '''
	sha=$(git rev-parse --short HEAD)
	tag=$(git describe --tags --abbrev=0 --match 'v*' | sed 's/^v//')
	sed -i "s/0.0.0-dev/$tag+$sha/" Cargo.toml
	sed -i "s/0.0.0_dev/$(echo $tag | sed 's/-/_/g')/" package/arch/PKGBUILD
	sed -i "s/0.0.0-dev/$tag/" package/debian/control
	sed -i "s/0.0.0.0/$(echo $tag | sed 's/[+-].*//g')/" package/windows/installer.wxs
'''

[tasks.artifact-dropoff]
script_runner = "sh"
script = "mkdir -p target/artifacts"

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.release-config]
dependencies = ["artifact-dropoff"]
script_runner = "sh"
script = "cp -a config.yml target/artifacts/config.yml"

[tasks.release-deb]
dependencies = ["artifact-dropoff", "patch-version", "build-release"]
condition = { platforms = ["linux"] }
script_runner = "sh"
script = '''
	bash package/debian/build.sh
	cp -a package/debian/*.deb target/artifacts/gravel-debian-x86_64.deb
'''

[tasks.release-tar]
dependencies = ["artifact-dropoff", "patch-version", "build-release"]
condition = { platforms = ["linux"] }
script_runner = "sh"
script = '''
	mkdir -p target/tmp/tar
	cp LICENSE target/tmp/tar/LICENSE
	cp config.yml target/tmp/tar/template-config.yml
	cp target/release/gravel target/tmp/tar/gravel
	(cd target/tmp/tar && tar czf ../../artifacts/gravel-linux-x86_64.tar.gz .)
'''

[tasks.release-archpkg]
dependencies = ["patch-version", "artifact-dropoff", "build-release"]
condition = { platforms = ["linux"] }
script_runner = "sh"
script = '''
	(cd package/arch && makepkg -Cf)
	cp -a package/arch/*.pkg.tar.zst target/artifacts/gravel-arch-x86_64.pkg.tar.zst
'''

[tasks.windows-exe]
dependencies = ["patch-version", "build-release"]
condition = { platforms = ["windows"] }
script_runner = "sh"
script = "rcedit target/release/gravel.exe --set-icon package/icons/icon.ico"

[tasks.release-zip]
dependencies = ["artifact-dropoff", "windows-exe"]
condition = { platforms = ["windows"] }
script_runner = "sh"
script = '''
	mkdir -p target/tmp/zip
	cp LICENSE target/tmp/zip/license.txt
	cp config.yml target/tmp/zip/template-config.yml
	cp target/release/gravel.exe target/tmp/zip/gravel.exe
	(cd target/tmp/zip && 7z a ../../artifacts/gravel-windows-x86_64.zip .)
'''

[tasks.release-msi]
dependencies = ["artifact-dropoff", "windows-exe"]
condition = { platforms = ["windows"] }
script_runner = "sh"
script = '''
	candle -arch x64 package/windows/installer.wxs -o target/installer.wixobj
	light -ext WixUIExtension -spdb target/installer.wixobj -o target/artifacts/gravel-windows-x86_64.msi
'''
