# NOTE: grep is super old on github actions windows-2022 so don't use it without LC_ALL=en_US.utf8
[tasks.patch-version]
script_runner = "sh"
script = '''
	sha=$(git rev-parse --short HEAD)
	tag=$(git describe --tags --abbrev=0 --match 'v*' | sed 's/^v//')
	sed -i "s/0.0.0-dev/$tag+$sha/" Cargo.toml
	sed -i "s/0.0.0_dev/$(echo $tag | sed 's/-/_/g')/" package/PKGBUILD
'''

[tasks.artifact-dropoff]
script_runner = "sh"
script = "mkdir -p target/artifacts"

[tasks.deb]
command = "cargo"
dependencies = ["artifact-dropoff", "patch-version"]
args = [
	"deb",
	"-p", "gravel",
	"-o", "target/artifacts/gravel-x86_64.deb",
]

[tasks.arch]
dependencies = ["patch-version", "artifact-dropoff"]
script = '''
	cargo build --release
	(cd package && makepkg -Cf)
	mv package/*.pkg.tar.zst target/artifacts/gravel-x86_64.pkg.tar.zst
'''

[tasks.build-exe]
command = "cargo"
dependencies = ["artifact-dropoff", "patch-version"]
args = ["build", "--release"]

[tasks.exe]
dependencies = ["build-exe"]
script = "mv target/release/gravel.exe target/artifacts/gravel-x86_64.exe"
