## Config for gravel's FLTK frontend.
## Remember to duplicate changes here in gravel's main config.

## Layout and sizing configuration.
layout:

  ## Scales all sizes by this factor. Useful for high DPI monitors.
  scale: 1.0

  ## Then maximum number of hits shown on screen. Any less and the window
  ## will shrink, any more and you will be able to scroll down the list.
  max_hits: 6

  ## Total window width. All other widths are calculated relative to this.
  window_width: 800

  ## These are some more specific values you usually don't need to change.
  hit_title_height: 30
  hit_title_font_size: 20
  hit_subtitle_height: 20
  hit_subtitle_font_size: 12
  query_font_size: 25
  scrollbar_width: 10
  scrollbar_padding: 3
  padding: 8

## Color configuration. Use the hex color: `0xRRGGBB`.
## Google has a color picker if you search for, well, "color picker".
colors:
  background: 0x202020
  accent: 0xbf6c0d
  text: 0xffffff

## Alternative representation which is more customizable.
## Chose *either* block, not both.
# colors:
  background: 0x202020
  query_text: 0xffffff
  query_cursor: 0xbf6c0d
  query_highlight: 0xbf6c0d
  hit_title: 0xffffff
  hit_subtitle: 0xffffff
  hit_highlight: 0xbf6c0d
  scrollbar: 0xbf6c0d

behaviour:

  ## Whether or not to show the window when starting gravel
  start_hidden: false

  ## Automatically hides the window when it loses focus.
  auto_hide: false

  ## Exits the application instead of hiding the window.
  ## Requires external solution to start gravel when desired.
  exit_on_hide: false

  ## Time in milliseconds after hiding in which show requests
  ## should be ignored. This is a workaround for weird behaviour
  ## in X11 where hotkeys steal focus.
  window_hide_debounce: 200

  ## Automatically centers the window on the screen each time it is shown.
  auto_center_window: true

  ## Shows the internal score assigned to each hit,
  ## useful for debugging purposes.
  show_scores: false
