[package]
name = "gravel-provider-exec"
version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
no-root = []

[dependencies]
gravel-ffi = { path = "../gravel-ffi" }

abi_stable.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["shellapi"] }

[lints]
workspace = true
