[package]
name = "gravel-provider-websearch"
version.workspace = true
edition.workspace = true

[dependencies]
gravel-ffi = { path = "../gravel-ffi" }

abi_stable.workspace = true
log.workspace = true
open.workspace = true
serde.workspace = true
urlencoding.workspace = true

[lints]
workspace = true
