[package]
name = "gravel-provider-websearch"
version.workspace = true
edition.workspace = true

[dependencies]
gravel-core = { path = "../gravel-core" }

anyhow.workspace = true
log.workspace = true
open.workspace = true
serde.workspace = true
urlencoding.workspace = true
