[package]
name = "gravel-provider-websearch"
version = "0.0.0"
edition = "2021"

[dependencies]
gravel-core = { path = "../gravel-core" }

anyhow.workspace = true
log.workspace = true
serde.workspace = true
urlencoding = "2.1.3"
