[package]
name = "gravel-provider-websearch"
version = "0.1.0"
edition = "2021"

[dependencies]
gravel-core = { path = "../gravel-core" }
gravel-util = { path = "../gravel-util" }
urlencoding = "2.1.0"
