[package]
name = "gravel-provider-program"
version.workspace = true
edition.workspace = true

[dependencies]
gravel-ffi = { path = "../gravel-ffi" }

abi_stable.workspace = true
glob.workspace = true
itertools.workspace = true
log.workspace = true
serde.workspace = true

[target.'cfg(unix)'.dependencies]
freedesktop_entry_parser.workspace = true

[target.'cfg(windows)'.dependencies]
shellexpand.workspace = true

[lints]
workspace = true
