[package]
name = "gravel-provider-program"
version = "0.1.0"
edition = "2021"

[dependencies]
gravel-core = { path = "../gravel-core" }
glob = "0.3.1"
shellexpand = "3.1.0"
serde = "1.0.188"

[target.'cfg(target_os = "linux")'.dependencies]
freedesktop_entry_parser = "1.3.0"
