## Config for gravel's program provider.
## Remember to duplicate changes here in gravel's main config.

## On linux, paths can be configured by changing the
## XDG_DATA_DIRS environment variable.

## Where to look for symlinks on Windows.
## Paths should be specified as globs.
paths_windows:
  - "$ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\**\\*.lnk"
  - "$APPDATA\\Microsoft\\Windows\\Start Menu\\Programs\\**\\*.lnk"
