## Config for gravel's program provider.
## Remember to duplicate changes here in gravel's main config.

## Where to look for freedesktop files on Linux.
## Paths should be specified as globs.
paths_linux:
  - "/usr/share/applications/*.desktop"
  - "/usr/local/share/applications/*.desktop"
  - "${XDG_DATA_HOME:-$HOME/.local/share}/applications/*.desktop"

## Where to look for symlinks on Windows.
## Paths should be specified as globs.
paths_windows:
  - "$ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\**\\*.lnk"
  - "$APPDATA\\Microsoft\\Windows\\Start Menu\\Programs\\**\\*.lnk"
