[package]
name = "gravel-provider-kill"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
gravel-core = { path = "../gravel-core" }

serde = "1.0.188"
sysinfo = "0.29.10"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.27.1", features = ["process", "signal"] }
