[package]
name = "gravel-provider-kill"
version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
no-root = []

[dependencies]
gravel-ffi = { path = "../gravel-ffi" }

abi_stable.workspace = true
anyhow.workspace = true
itertools.workspace = true
log.workspace = true

[target.'cfg(windows)'.dependencies]
sysinfo.workspace = true
winapi.workspace = true
thiserror.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["process", "signal"] }
procfs.workspace = true

[lints]
workspace = true
