[package]
name = "gravel-frontend-default"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = { version = "1.2.31", features = ["fltk-bundled"] }
gravel-core = { path = "../gravel-core" }
lazy_static = "1.4.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
