[package]
name = "gravel-frontend-default"
version = "0.1.0"
edition = "2021"

[dependencies]
gravel-core = { path = "../gravel-core" }

fltk = { version = "^1.4", features = ["fltk-bundled"] }
lazy_static = "1.4.0"
serde = "1.0.188"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
