[package]
name = "gravel-core"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.12.0"
enumflags2 = "0.7.3"
fuzzy-matcher = "0.3.7"
hotkey = "0.3.1"
serde = "1.0.136"
shellexpand = "2.1.0"
