[package]
name = "gravel-core"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.13.3"
enumflags2 = "0.7.8"
fuzzy-matcher = "0.3.7"
hotkey = "0.3.1"
itertools = "0.11.0"
lazy_static = "1.4.0"
serde = "1.0.188"
