[package]
name = "gravel-core"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.13.3"
enumflags2 = "0.7.7"
fuzzy-matcher = "0.3.7"
hotkey = "0.3.1"
serde = "1.0.183"
shellexpand = "3.1.0"
