[package]
name = "gravel"
version.workspace = true
edition.workspace = true
description = "cross-platform run launcher"
readme = "../README.md"
license = "GPL-3"
authors = ["thorou"]
repository = "https://github.com/thorio/gravel"

[features]
default = [ "builtins" ]

builtins = [ "fltk", "calculator", "exec", "kill", "program", "system", "websearch" ]
fltk = ["gravel-frontend-fltk"]
calculator = ["gravel-provider-calculator"]
exec = ["gravel-provider-exec"]
kill = ["gravel-provider-kill"]
program = ["gravel-provider-program"]
system = ["gravel-provider-system"]
websearch = ["gravel-provider-websearch"]

[dependencies]
gravel-core = { path = "../gravel-core" }
gravel-ffi = { path = "../gravel-ffi" }

gravel-frontend-fltk = { path = "../gravel-frontend-fltk", features = ["no-root"], optional = true }
gravel-provider-calculator = { path = "../gravel-provider-calculator", features = ["no-root"], optional = true }
gravel-provider-exec = { path = "../gravel-provider-exec", features = ["no-root"], optional = true }
gravel-provider-kill = { path = "../gravel-provider-kill", features = ["no-root"], optional = true }
gravel-provider-program = { path = "../gravel-provider-program", features = ["no-root"], optional = true }
gravel-provider-system = { path = "../gravel-provider-system", features = ["no-root"], optional = true }
gravel-provider-websearch = { path = "../gravel-provider-websearch", features = ["no-root"], optional = true }

abi_stable.workspace = true
anyhow.workspace = true
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
clap-verbosity-flag.workspace = true
color-eyre = { workspace = true, features = ["issue-url"] }
fern.workspace = true
file-rotate.workspace = true
glob.workspace = true
hostname.workspace = true
itertools.workspace = true
log.workspace = true
single-instance.workspace = true
stderrlog.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["wincon"] }

[target.'cfg(unix)'.dependencies]
exec.workspace = true

[dev-dependencies]
gravel-test-utils = { path = "../gravel-test-utils" }

rstest.workspace = true
test_bin.workspace = true

[lints]
workspace = true
