[package]
name = "gravel-provider-custom"
version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
no-root = []

[dependencies]
gravel-ffi = { path = "../gravel-ffi" }

abi_stable.workspace = true
log.workspace = true
serde.workspace = true
nonempty = { workspace = true, features = ["serialize"] }

[lints]
workspace = true
