[package]
name = "gravel-provider-system"
version = "0.1.0"
edition = "2021"

[dependencies]
gravel-core = { path = "../gravel-core" }

serde = "1.0.136"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["powrprof"] }
system_shutdown = "3.0.0"
