[package]
name = "gravel-provider-system"
version.workspace = true
edition.workspace = true

[dependencies]
gravel-ffi = { path = "../gravel-ffi" }

abi_stable.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["powrprof"] }
system_shutdown.workspace = true

[lints]
workspace = true
