## Config for gravel's system provider.
## Remember to duplicate changes here in gravel's main config.

## Below are configurable titles and subtitles for each command.
## Linux systems can additionally configure a bash commmand to be run.
## On Windows systems, the native API is used instead.

exit:
  title: exit
  subtitle: Exit gravel

reload:
  title: reload
  subtitle: Reload gravel

lock:
  title: lock
  subtitle: Lock the System

  ## Specifies the bash command to run on linux systems.
  command_linux: loginctl lock-session

logout:
  title: log out
  subtitle: Close the current session
  command_linux: loginctl terminate-session $(loginctl session-status | awk 'NR==1{print $1}')

restart:
  title: restart
  subtitle: Restart the System
  command_linux: shutdown -r now

shutdown:
  title: shutdown
  subtitle: Shut the System down
  command_linux: shutdown now

sleep:
  title: sleep
  subtitle: Put the System to sleep
  command_linux: systemctl suspend
