name: check

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

env:
  RUSTDOCFLAGS: "-D warnings"
  RUSTFLAGS: "-D warnings"

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpango1.0-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-bin libwayland-dev wayland-protocols libdbus-1-dev libxkbcommon-dev xdg-utils xvfb -y --no-install-recommends

      - name: checkout repository
        uses: actions/checkout@v4

      - name: check
        run: cargo make --no-workspace ci-check

  windows:
    runs-on: windows-2022
    steps:
      - name: setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: checkout repository
        uses: actions/checkout@v4

      - name: check
        run: cargo make --no-workspace ci-check
