name: publish

on:
  push:
    tags: [ 'v*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: install tools
        run: |
          sudo apt-get update
          sudo apt-get install libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpango1.0-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-bin xdg-utils -y
          cargo install --debug cargo-make

      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: build and package
        run: cargo make --no-workspace deb

      - name: upload packages
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: target/artifacts/*

  arch:
    runs-on: ubuntu-22.04
    container:
      image: archlinux
    permissions:
      contents: write
    steps:
      - name: install tools
        run: pacman -Syu base-devel rustup git sudo --noconfirm

      - name: setup build user
        run: useradd builder -m

      - name: install rust tools
        shell: sudo -u builder bash {0}
        run: |
          rustup default stable
          cargo install --debug cargo-make

      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: fix permissions
        run: chown -R builder:builder .

      - name: install dependencies
        run: source package/arch/PKGBUILD && pacman -S ${depends[@]} --noconfirm

      - name: build and package
        shell: sudo -u builder bash {0}
        run: cargo make --no-workspace arch

      - name: upload packages
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: target/artifacts/*

  windows:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: install rust tools
        run: cargo install --debug cargo-make

      - name: install rcedit
        run: curl https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe -Lo C:/Windows/rcedit.exe

      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: build and package
        run: cargo make --no-workspace exe

      - name: upload packages
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: target/artifacts/*
